name: Hello World Workflow

on:
  push:
    branches: [main]

jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Run Hello World
        run: python main.py
        
